---
- hosts:        127.0.0.1
  connection:   local
  vars:

      docker_brew: &docker_brew
        - docker
        - docker-machine
        - docker-compose

      third_party_brew: &third_party_brew
        - amazon-ecs-cli
        - kubernetes-cli

      third_party_cask_brew: &third_party_cask_brew
        - minikube

  tasks:

  - name: Update Homebrew
    homebrew: update_homebrew=yes

  - name: Update Ansible
    homebrew: name=ansible state=latest

  - name: Check for VMware Fusion
    shell: ls /Applications/ | grep -i "VMware Fusion"
    register: fusion_installed
    ignore_errors: True

  - name: Check for Virtualbox
    shell: ls /Applications/ | grep -i "VirtualBox"
    register: virtualbox_installed
    ignore_errors: True

  - name: Install Virtualbox
    homebrew_cask: name=virtualbox state=present
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    when: fusion_installed.rc !=0  and virtualbox_installed.rc !=0

  - stat: path=/usr/local/bin/docker
    register: sym

  - name: Install Docker tools
    when: sym.stat.islnk is not defined or sym.stat.islnk
    homebrew: >
      name={{item}}
      state=latest
    with_items: *docker_brew

  - name: Install third-party tools
    homebrew: >
      name={{item}}
      state=latest
    with_items: *third_party_brew

  - name: Install third-party tools from cask (May ask for sudo passwd)
    homebrew_cask: >
      name={{item}}
      state=installed
    with_items: *third_party_cask_brew
