---
- hosts:        127.0.0.1
  connection:   local
  vars:

      brew_commit: HEAD

      docker_brew: &docker_brew
        - docker-machine
        - docker-compose
        - docker

      third_party_brew: &third_party_brew
        - amazon-ecs-cli
        - kubernetes-cli

  tasks:

  - name: Update Homebrew
    homebrew: update_homebrew=yes

  - name: Tap Caskroom
    homebrew_tap: tap=caskroom/cask

  - name: Install Caskroom
    homebrew: name=brew-cask state=latest

  - name: Check for VMware Fusion
    shell: ls /Applications/ | grep -i "VMware Fusion"
    register: fusion_installed
    ignore_errors: True

  - name: Check for Virtualbox
    shell: ls /Applications/ | grep -i "VirtualBox"
    register: virtualbox_installed
    ignore_errors: True

  - name: Install Virtualbox
    homebrew_cask: name=virtualbox state=present
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    when: fusion_installed.rc !=0  and virtualbox_installed.rc !=0

  - stat: path=/usr/local/bin/docker
    register: sym

  - name: Remove docker tools for a clean install
    when: sym.stat.islnk is not defined or sym.stat.islnk
    shell: brew uninstall --force {{ item }}
    with_items: *docker_brew

  - name: Update brew shallow commit to depth=1000
    when: sym.stat.islnk is not defined or sym.stat.islnk
    shell: git -C $(brew --prefix) fetch --depth=10000 origin master

  - name: Checkout brew commit {{ brew_commit }}
    when: sym.stat.islnk is not defined or sym.stat.islnk
    shell: git -C $(brew --prefix) checkout {{ brew_commit }}

  - name: Install Docker tools
    when: sym.stat.islnk is not defined or sym.stat.islnk
    shell: brew install {{ item }}
    ignore_errors: True
    with_items: *docker_brew

  - name: Install Docker third-party tools
    homebrew: >
      name={{item}}
      state=latest
    ignore_errors: True
    with_items: *third_party_brew

  - name: Revert brew back to master
    when: sym.stat.islnk is not defined or sym.stat.islnk
    shell: git -C $(brew --prefix) checkout master
