---
- hosts:        127.0.0.1
  connection:   local
  vars:

      uid:
      gid:
      mnet:

      docker_brew: &docker_brew
        - docker-machine
        - docker-compose
        - docker

      third_party_brew: &third_party_brew
        - amazon-ecs-cli
        - kubernetes-cli

  tasks:

  - name: Update Homebrew
    homebrew: update_homebrew=yes

  - name: Tap Caskroom
    homebrew_tap: tap=caskroom/cask

  - name: Install Caskroom
    homebrew: name=brew-cask state=latest

  - name: Check for VMware Fusion
    shell: ls /Applications/ | grep -i "VMware Fusion"
    register: fusion_installed
    ignore_errors: True

  - name: Check for Virtualbox
    shell: ls /Applications/ | grep -i "VirtualBox"
    register: virtualbox_installed
    ignore_errors: True

  - name: Install Virtualbox
    homebrew_cask: name=virtualbox state=present
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    when: fusion_installed.rc !=0  and virtualbox_installed.rc !=0

  - stat: path=/usr/local/bin/docker
    register: sym

  - name: Add NFS share to /etc/exports
    blockinfile:
      dest: /etc/exports
      create: yes
      marker: "## {mark} Boot2Docker Developer Environment ##"
      content: '/Users -alldirs -network {{ mnet }} -mask 255.255.0.0 -mapall={{ uid }}:{{ gid }}'
    become: yes
    become_method: sudo
    register: exports

  - name: Restart nfsd
    command: sudo nfsd restart
    become: yes
    become_method: sudo
    when: exports.changed

  - name: Install Docker tools
    when: sym.stat.islnk is not defined or sym.stat.islnk
    homebrew: >
      name={{item}}
      state=latest
    with_items: *docker_brew

  - name: Install Docker third-party tools
    homebrew: >
      name={{item}}
      state=latest
    with_items: *third_party_brew
